
SET IDENTITY_INSERT [dbo].[tblUser] ON 
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (1, 2, N'XXXXXXXXX', N'ND2Ug1f6cx8DnmFVnCgYVdhPwJFsYX5kfR4a33ITZdguJUxKIDrhsYDbgrEOPqUDv/HMBUEn/nhqslgR5YT35Q==', N'PBESSPIPQOEVXLHSWDYS', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', 1, N'XXXXXXXXX', N'XXXXXXXXX ', 0, 1, 1, 1, 0, 0, CAST(N'2018-10-23T15:39:06.950' AS DateTime), CAST(N'2018-12-08T12:49:12.810' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (2, 1, N'668310162', N't/6MTquEgHtlTuT4O5y9dqMYTfLm9NXvtTB4K6RT09ziOeb1VhJoB7t+gGSIsTC2JLZmB+ZeAiOdXq9/U5Gv2A==', N'FAJSIAKCEJWTJWYRTFGJ', N'668310162', N'seba.olejarz@gmail.com', N'Sebastian', N'Olejarz', 1, N'Test sp. z o.o.', N'          ', 0, 1, 1, 1, 0, 1, CAST(N'2018-10-22T19:16:31.070' AS DateTime), CAST(N'2018-12-09T21:48:14.093' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (3, 1, N'509604544', N'kCtbzRNKScGfY2ib91Htr6X9UlDYyGHQgO9O92Dm3m5rUL/BP9qPqbJCdJs5LaF1PCz7kHUSuJnWvCG4JgwE3Q==', N'GKVMXEXWBACVTPTQCPYM', N'509604544', N'', N'Agata Br', N'', 0, N'', N'          ', 1, 0, 1, 1, 0, 1, CAST(N'2018-11-15T20:16:49.510' AS DateTime), CAST(N'2018-12-09T20:19:37.403' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (4, 2, N'503860775', N'hmc/OwP78bXX0+GzVCds47lgS8ZQ6bIE0hWXPo2vw5Q4w31gYIuFLT6z2Qr8huZe5dliRTJ5a+Xl2zDsuIbh5Q==', N'EOBUSITXIANXLTQAGNOK', N'503860775', N'malina589@gmail.com', N'Alina', N'Kubowicz', 0, N'', N'          ', 0, 0, 1, 1, 1, 1, CAST(N'2018-12-01T20:50:40.633' AS DateTime), CAST(N'2018-12-02T14:20:09.090' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (6, 2, N'507117437', N'/lFZu55uiRWEEJ4bwE1chwHEGe886Nji6bqeYtGBjwQcCt5oytrnjLVM5BovHDxO5dwj+dv5KDPUzux/2Qtj1Q==', N'IKQUMOSDIVWHGMRELJNO', N'507117437', N'', N'Marta B', N'', 0, N'', N'          ', 0, 0, 1, 1, 1, 1, CAST(N'2018-12-04T16:35:36.490' AS DateTime), CAST(N'2018-12-09T19:02:06.230' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (7, 2, N'782126785', N'7ALs2fwVki8T1rTgvDFLdg24AKrYUL/3SAPuOG36gDxFKDBFrFGNQawBAUnxH31kdbRnQZ1DtAZFHw2cPBj7eQ==', N'MMBEWFIRGHIVMCHWDUTK', N'782126785', N'', N'Agatka', N'Sałatka', 1, N'Fajny Sklep', N'1101112221', 1, 1, 1, 1, 0, 1, CAST(N'2018-12-04T21:19:07.050' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (8, 1, N'501362032', N'awHL5/E5D6F3nhXQQN6bXbWKDa4tNEs6JtQR9wGbIrefzVvuFLsmJaXqmC5jLkq5IRWaRv36qy7fiYIAk+o3Qg==', N'XYUUSSMFSFURWCSXMXOF', N'501362032', N'', N'Rafał', N'Kubowicz', 1, N'devdt testowy Rafał Kubowicz', N'1231231231', 0, 1, 1, 1, 0, 1, CAST(N'2018-12-08T11:53:27.633' AS DateTime), CAST(N'2018-12-08T11:56:46.227' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (122, 2, N'506145982', N'pass1', N'pasSalt', N'506145982', N'', N'Ada', N'Chojnacka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.043' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (123, 2, N'606344734', N'pass1', N'pasSalt', N'606344734', N'', N'Adam', N'Kochanowski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.070' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (124, 2, N'602183923', N'pass1', N'pasSalt', N'602183923', N'', N'Adaś', N'Kulcenty', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.100' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (125, 2, N'515256070', N'pass1', N'pasSalt', N'515256070', N'', N'Agata', N'Kwiaciarnia', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.120' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (126, 2, N'510292085', N'pass1', N'pasSalt', N'510292085', N'', N'Agnieszka', N'Dopieralska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.143' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (127, 2, N'668344300', N'pass1', N'pasSalt', N'668344300', N'', N'Agnieszka', N'Dubiel', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.170' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (128, 2, N'500419233', N'pass1', N'pasSalt', N'500419233', N'', N'Agnieszka', N'Himiecka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.197' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (129, 2, N'539692179', N'pass1', N'pasSalt', N'539692179', N'', N'Agnieszka', N'Kołakowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.250' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (130, 2, N'604225116', N'pass1', N'pasSalt', N'604225116', N'', N'Agnieszka', N'Małkiewicz', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.277' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (131, 2, N'507386978', N'pass1', N'pasSalt', N'507386978', N'', N'Agnieszka', N'Perkowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.317' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (132, 2, N'882814834', N'pass1', N'pasSalt', N'882814834', N'', N'Albert', N'Dębski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.380' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (133, 2, N'784567707', N'pass1', N'pasSalt', N'784567707', N'', N'Alicja', N'Jabłońska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.417' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (134, 2, N'602153559', N'pass1', N'pasSalt', N'602153559', N'', N'Andrzej', N'Markowski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.447' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (135, 2, N'608640143', N'pass1', N'pasSalt', N'608640143', N'', N'Ania', N'Wiewiórska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.480' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (136, 2, N'602205574', N'pass1', N'pasSalt', N'602205574', N'', N'Ania', N'Joga Jabłonna', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.510' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (137, 2, N'668045672', N'pass1', N'pasSalt', N'668045672', N'', N'Ania', N'Kołodziejska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.530' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (138, 2, N'698965984', N'pass1', N'pasSalt', N'698965984', N'', N'Ania', N'Michalska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.560' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (139, 2, N'695512020', N'pass1', N'pasSalt', N'695512020', N'', N'Anka', N'Sarnacka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.587' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (140, 2, N'607235906', N'pass1', N'pasSalt', N'607235906', N'', N'Anna', N'Grzelecka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.610' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (141, 2, N'501826323', N'pass1', N'pasSalt', N'501826323', N'', N'Anna', N'Kołodziej', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.630' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (142, 2, N'730850660', N'pass1', N'pasSalt', N'730850660', N'', N'Anna', N'Łojowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.653' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (143, 2, N'537333120', N'pass1', N'pasSalt', N'537333120', N'', N'Anna', N'Sławkowska-Rode', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.680' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (144, 2, N'664558683', N'pass1', N'pasSalt', N'664558683', N'', N'Artur', N'Amahl', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.703' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (145, 2, N'606274246', N'pass1', N'pasSalt', N'606274246', N'', N'Bartek', N'Chruśliński', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.727' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (146, 2, N'603069609', N'pass1', N'pasSalt', N'603069609', N'', N'Bożena', N'Majewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.743' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (147, 2, N'784047135', N'pass1', N'pasSalt', N'784047135', N'', N'Bożena', N'Szomańska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.767' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (148, 2, N'798111168', N'pass1', N'pasSalt', N'798111168', N'', N'Czarek', N'Skóra', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.793' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (149, 2, N'606580666', N'pass1', N'pasSalt', N'606580666', N'', N'Damian', N'Przewodowski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.817' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (150, 2, N'509830525', N'pass1', N'pasSalt', N'509830525', N'', N'Dorota', N'Bąk-Gajda', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.843' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (151, 2, N'501506581', N'pass1', N'pasSalt', N'501506581', N'', N'Dorota', N'Kozłowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.870' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (152, 2, N'600438677', N'pass1', N'pasSalt', N'600438677', N'', N'Edyta', N'Elert', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.893' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (153, 2, N'607107090', N'pass1', N'pasSalt', N'607107090', N'', N'Edyta', N'Pelc', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.920' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (154, 2, N'501385400', N'pass1', N'pasSalt', N'501385400', N'', N'Ela', N'Dzierzgowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.943' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (155, 2, N'600664348', N'pass1', N'pasSalt', N'600664348', N'', N'Elżbieta', N'Rostecka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.967' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (156, 2, N'505614574', N'pass1', N'pasSalt', N'505614574', N'', N'Ewa', N'Błaszkowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:24.997' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (157, 2, N'664486768', N'pass1', N'pasSalt', N'664486768', N'', N'Ewa', N'Chorążak', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:25.023' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (158, 2, N'723029470', N'pass1', N'pasSalt', N'723029470', N'', N'Ewa', N'Drabikowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:25.050' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (159, 2, N'607059250', N'pass1', N'pasSalt', N'607059250', N'', N'Ewa', N'Golańska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:25.070' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (160, 2, N'788053941', N'pass1', N'pasSalt', N'788053941', N'', N'Ewa', N'Kiełtyka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:25.093' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (161, 2, N'883386606', N'pass1', N'pasSalt', N'883386606', N'', N'Ewelina', N'Gładki', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:25.410' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (162, 2, N'663190341', N'pass1', N'pasSalt', N'663190341', N'', N'Gosia', N'Grotkiewicz', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.417' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (163, 2, N'501218702', N'pass1', N'pasSalt', N'501218702', N'', N'Gośka', N'Kalicka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.437' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (164, 2, N'600356000', N'pass1', N'pasSalt', N'600356000', N'', N'Gośka', N'Majewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.460' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (165, 2, N'606273492', N'pass1', N'pasSalt', N'606273492', N'', N'Gośka', N'Paciorek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.483' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (166, 2, N'601393215', N'pass1', N'pasSalt', N'601393215', N'', N'Grzegorz', N'Białecki', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.507' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (167, 2, N'600213417', N'pass1', N'pasSalt', N'600213417', N'', N'Grzegorz', N'Paciorek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.540' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (168, 2, N'501867534', N'pass1', N'pasSalt', N'501867534', N'', N'Grzesiek', N'Grochowski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.567' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (169, 2, N'501150950', N'pass1', N'pasSalt', N'501150950', N'', N'Halina', N'Potocka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.587' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (170, 2, N'600589592', N'pass1', N'pasSalt', N'600589592', N'', N'Ilona', N'Dudek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.620' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (171, 2, N'510103717', N'pass1', N'pasSalt', N'510103717', N'', N'Inga', N'Borzecka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.640' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (172, 2, N'884694100', N'pass1', N'pasSalt', N'884694100', N'', N'Iwona', N'Dudek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.663' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (173, 2, N'732782557', N'pass1', N'pasSalt', N'732782557', N'', N'Iwona', N'Dziekańska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.683' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (174, 2, N'509496176', N'pass1', N'pasSalt', N'509496176', N'', N'Iwona', N'Jędruszek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.703' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (175, 2, N'609567878', N'pass1', N'pasSalt', N'609567878', N'', N'Iza', N'Paderewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.737' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (176, 2, N'506118476', N'pass1', N'pasSalt', N'506118476', N'', N'Iza', N'Pańkowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.770' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (177, 2, N'510127266', N'pass1', N'pasSalt', N'510127266', N'', N'Iza', N'Przewodowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.790' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (178, 2, N'602597822', N'pass1', N'pasSalt', N'602597822', N'', N'Izabela', N'Nowakowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.810' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (179, 2, N'501705530', N'pass1', N'pasSalt', N'501705530', N'', N'Jacek', N'Zalewski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.860' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (180, 2, N'508211188', N'pass1', N'pasSalt', N'508211188', N'', N'Jerzy', N'Krajewski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.880' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (181, 2, N'696434878', N'pass1', N'pasSalt', N'696434878', N'', N'Joanna', N'Gładki', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.903' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (182, 2, N'661683562', N'pass1', N'pasSalt', N'661683562', N'', N'Joanna', N'Walewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.920' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (183, 2, N'797347707', N'pass1', N'pasSalt', N'797347707', N'', N'Jola', N'Gutowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.943' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (184, 2, N'601051249', N'pass1', N'pasSalt', N'601051249', N'', N'Jola', N'Samsel', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.967' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (185, 2, N'501867241', N'pass1', N'pasSalt', N'501867241', N'', N'Jola', N'Zalewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:26.987' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (186, 2, N'510632695', N'pass1', N'pasSalt', N'510632695', N'', N'Julia', N'Marty', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.013' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (187, 2, N'502167634', N'pass1', N'pasSalt', N'502167634', N'', N'Julita', N'Chomik', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.050' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (188, 2, N'538811232', N'pass1', N'pasSalt', N'538811232', N'', N'Justyna ', N'Kołaczek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.077' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (189, 2, N'606393062', N'pass1', N'pasSalt', N'606393062', N'', N'Karol', N'Stachurski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.100' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (190, 2, N'784084471', N'pass1', N'pasSalt', N'784084471', N'', N'Karolina', N'Basaj', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.137' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (191, 2, N'508104370', N'pass1', N'pasSalt', N'508104370', N'', N'Kasia', N'Chojnacka', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.160' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (192, 2, N'503377500', N'pass1', N'pasSalt', N'503377500', N'', N'Kaśka', N'Węgrzynowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.180' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (193, 2, N'509535683', N'pass1', N'pasSalt', N'509535683', N'', N'Katarzyna', N'Zbroch', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.207' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (194, 2, N'501076803', N'pass1', N'pasSalt', N'501076803', N'', N'Kazimierz', N'Wysocki', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.230' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (195, 2, N'601595946', N'pass1', N'pasSalt', N'601595946', N'', N'Kooperatywa Południowa', N'Białkowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.250' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (196, 2, N'694635334', N'pass1', N'pasSalt', N'694635334', N'', N'Krystyna', N'Grabowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.283' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (197, 2, N'509200907', N'pass1', N'pasSalt', N'509200907', N'', N'Krystyna', N'Kwasiborska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.313' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (198, 2, N'601135131', N'pass1', N'pasSalt', N'601135131', N'', N'Pani', N'Krzemińska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.347' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (199, 2, N'605408084', N'pass1', N'pasSalt', N'605408084', N'', N'Pan', N'Latyfowicz', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.373' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (200, 2, N'604092008', N'pass1', N'pasSalt', N'604092008', N'', N'Lechu', N'Smuniewski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.397' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (201, 2, N'510919483', N'pass1', N'pasSalt', N'510919483', N'', N'Lidia', N'Piendyk', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.423' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (202, 2, N'604766702', N'pass1', N'pasSalt', N'604766702', N'', N'Łukasz', N'Chruśliński', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.450' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (203, 2, N'609991091', N'pass1', N'pasSalt', N'609991091', N'', N'Magda', N'Deć', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.477' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (204, 2, N'502337476', N'pass1', N'pasSalt', N'502337476', N'', N'Magda', N'Kujawa', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.503' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (205, 2, N'502731914', N'pass1', N'pasSalt', N'502731914', N'', N'Magda', N'Maksylewicz', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.530' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (206, 2, N'505159885', N'pass1', N'pasSalt', N'505159885', N'', N'Magda', N'Smuniewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.557' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (207, 2, N'507181175', N'pass1', N'pasSalt', N'507181175', N'', N'Magdalena', N'Boratyńska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.583' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (208, 2, N'609116262', N'pass1', N'pasSalt', N'609116262', N'', N'Magdalena', N'Majewska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.603' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (209, 2, N'793082893', N'pass1', N'pasSalt', N'793082893', N'', N'Magdalena', N'Paradowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.623' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (210, 2, N'733916230', N'pass1', N'pasSalt', N'733916230', N'', N'Marcin', N'Dziekański', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.667' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (211, 2, N'604831532', N'pass1', N'pasSalt', N'604831532', N'', N'Marcin', N'Grodzki', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.757' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (212, 2, N'531994004', N'pass1', N'pasSalt', N'531994004', N'', N'Marek', N'Kalicki', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.777' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (213, 2, N'603488301', N'pass1', N'pasSalt', N'603488301', N'', N'Mariola', N'Klocek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.800' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (214, 2, N'691666723', N'pass1', N'pasSalt', N'691666723', N'', N'Marta ', N'Drubkowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.820' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (215, 2, N'727412654', N'pass1', N'pasSalt', N'727412654', N'', N'Marta', N'Sosińska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.843' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (216, 2, N'608336171', N'pass1', N'pasSalt', N'608336171', N'', N'Matka', N'Teresa', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.877' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (217, 2, N'506270957', N'pass1', N'pasSalt', N'506270957', N'', N'Mira', N'Kowalska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.897' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (218, 2, N'502322116', N'pass1', N'pasSalt', N'502322116', N'', N'Monika', N'Grochowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.920' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (219, 2, N'696678231', N'pass1', N'pasSalt', N'696678231', N'', N'Pani', N'Muszyńska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.960' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (220, 2, N'608672318', N'pass1', N'pasSalt', N'608672318', N'', N'Norbert', N'Drubkowski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:27.980' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (221, 2, N'793103400', N'pass1', N'pasSalt', N'793103400', N'', N'Dominik Olo', N'Olszewski', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.007' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (222, 2, N'697082649', N'pass1', N'pasSalt', N'697082649', N'', N'Pani', N'Pakulska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.033' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (223, 2, N'503873410', N'pass1', N'pasSalt', N'503873410', N'', N'Pan', N'Zegadło', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.100' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (224, 2, N'691032090', N'pass1', N'pasSalt', N'691032090', N'', N'Paweł', N'Gabrysiak', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.143' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (225, 2, N'513930520', N'pass1', N'pasSalt', N'513930520', N'', N'Radek', N'Raczkiewicz', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.167' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (226, 2, N'604255324', N'pass1', N'pasSalt', N'604255324', N'', N'Radziu', N'Chyliński', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.200' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (227, 2, N'601802004', N'pass1', N'pasSalt', N'601802004', N'', N'Regina', N'Zep', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.220' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (228, 2, N'604513872', N'pass1', N'pasSalt', N'604513872', N'', N'Robert', N'Basałaj', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.243' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (229, 2, N'502918125', N'pass1', N'pasSalt', N'502918125', N'', N'Wanda', N'Makowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.270' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (230, 2, N'609117325', N'pass1', N'pasSalt', N'609117325', N'', N'Wiesława', N'Książek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.300' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (231, 2, N'795487555', N'pass1', N'pasSalt', N'795487555', N'', N'Wiolka', N'Przewodowska', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.323' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (232, 2, N'516123121', N'pass1', N'pasSalt', N'516123121', N'', N'Władek', N'Jędruszek', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.347' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (233, 2, N'602115976', N'pass1', N'pasSalt', N'602115976', N'', N'Pani', N'Żyszkowicz', 0, N'', N'          ', 0, 0, 1, 1, 0, 1, CAST(N'2018-12-09T16:00:28.377' AS DateTime), NULL)
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (234, 2, N'XXXXXXXXX', N'PwOGuJxBkgKyYAR46786vAgyu0QMVDIBJn0eauV5OZvXJV2EjcYJPEczx9IWC+vxcYbzXPZ9O2Dthw8UTFqPGQ==', N'JWVXVCSUPYCEIMTTFDXQ', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', 1, N'XXXXXXXXX', N'XXXXXXXXX ', 1, 1, 1, 1, 0, 0, CAST(N'2018-12-09T16:25:19.487' AS DateTime), CAST(N'2018-12-09T18:27:02.033' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (235, 2, N'123123123', N'FyPWcrgeu38j8qOUBkUsQv4CUP0wvsGpb3WJmSgRu6W0fgWoGDGr1RO1ZNcWD5URCvm046LrdnrrmSGUArTcDA==', N'PJJKOFYOVMHCBRDWFKKC', N'123123123', N'', N'testowa', N'janusza', 1, N'januszowy test', N'1231231231', 0, 1, 1, 0, 0, 0, CAST(N'2018-12-09T17:15:51.510' AS DateTime), CAST(N'2018-12-09T20:59:24.790' AS DateTime))
GO
INSERT [dbo].[tblUser] ([UserID], [UserRoleID], [LoginName], [PasswordHash], [PasswordSalt], [PhoneNumber], [Email], [FirstName], [LastName], [IsBusinessClient], [CompanyName], [NIP], [IsWholesalePriceActive], [IsDeliveryActive], [IsGDPRAccepted], [IsMarketingAccepted], [IsKDR], [IsActive], [DateCreated], [LastUpdated]) VALUES (236, 2, N'725286000', N'Z4R2ek/ntsoHxbXg3ANWjfOeuYNQVtD2TsHgftbZNdiXeFUTOxIUYgRUb/LxVuZiyH174XM/QQb2Kt8E7/6szw==', N'VPFDEFNHPNMCLYKFSNKL', N'725286000', N'', N'Michaś', N'', 1, N'Michasiowa Górka', N'1112225551', 0, 1, 1, 1, 0, 1, CAST(N'2018-12-09T18:29:33.937' AS DateTime), CAST(N'2018-12-09T18:33:19.637' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[tblUser] OFF
GO
SET IDENTITY_INSERT [dbo].[tblAddress] ON 
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (1, 1, N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XX-XXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', 1, 1, CAST(N'2018-12-01T21:07:49.887' AS DateTime), CAST(N'2018-12-08T11:52:00.163' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (2, 7, N'Mickiewicza', N'5', N'', N'Legionowo', N'', N'05-120', N'Agata', N'Sałata', N'22 778 55 88', 0, 1, CAST(N'2018-12-04T21:23:09.503' AS DateTime), CAST(N'2018-12-09T16:17:31.913' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (3, 8, N'Rzeźnicza', N'10', N'23', N'Kraków', N'', N'31-540', N'', N'', N'', 1, 1, CAST(N'2018-12-08T11:57:03.123' AS DateTime), NULL)
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (4, 7, N'Marszałkowska', N'15', N'', N'Warszawa', N'', N'00-120', N'Nusz', N'Malina', N'666555444', 0, 1, CAST(N'2018-12-09T16:16:42.817' AS DateTime), CAST(N'2018-12-09T16:17:31.913' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (5, 7, N'Modlińska', N'100', N'', N'Nowy Dwór Mazowiecki', N'', N'88-111', N'sobie', N'Taaaak', N'999000111', 1, 1, CAST(N'2018-12-09T16:17:31.913' AS DateTime), NULL)
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (6, 234, N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XX-XXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', 0, 1, CAST(N'2018-12-09T16:28:13.587' AS DateTime), CAST(N'2018-12-09T18:27:02.033' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (7, 234, N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XX-XXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', 0, 1, CAST(N'2018-12-09T16:28:44.613' AS DateTime), CAST(N'2018-12-09T18:27:02.033' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (8, 234, N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XX-XXX', N'XXXXXXXXX', N'XXXXXXXXX', N'XXXXXXXXX', 1, 1, CAST(N'2018-12-09T16:29:20.043' AS DateTime), CAST(N'2018-12-09T18:27:02.033' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (9, 236, N'Hubala', N'13', N'', N'Legionowo', N'', N'05-120', N'HHHH', N'Wiera', N'888777111', 0, 1, CAST(N'2018-12-09T18:38:09.097' AS DateTime), CAST(N'2018-12-09T18:39:18.707' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (10, 236, N'Postępu ', N'66', N'', N'Warszawa', N'', N'00-120', N'Góra', N'Teresa', N'999000111', 0, 1, CAST(N'2018-12-09T18:38:39.120' AS DateTime), CAST(N'2018-12-09T18:39:18.707' AS DateTime))
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (11, 236, N'Marszałkowska ', N'16', N'', N'Warszawa', N'', N'88-111', N'Pod Sufitem', N'Równo', N'555111555', 1, 1, CAST(N'2018-12-09T18:39:18.710' AS DateTime), NULL)
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (12, 235, N'Rzeźnicza', N'10', N'23', N'Kraków', N'', N'31-540', N'', N'asd', N'', 1, 1, CAST(N'2018-12-09T20:42:58.383' AS DateTime), NULL)
GO
INSERT [dbo].[tblAddress] ([AddressID], [UserID], [Street], [NumberLine1], [NumberLine2], [City], [State], [ZipCode], [ContactPersonFirstName], [ContactPersonLastName], [ContactPhoneNumber], [IsMainAddress], [IsActive], [DateCreated], [LastUpdated]) VALUES (13, 2, N'Sezamkowa', N'100', N'5', N'Swedziszów', N'', N'99-999', N'Janko', N'Muzykant', N'999888777', 1, 1, CAST(N'2018-12-09T21:50:48.283' AS DateTime), NULL)
GO
SET IDENTITY_INSERT [dbo].[tblAddress] OFF
GO
SET IDENTITY_INSERT [dbo].[tblProduct] ON 
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (1, 1, N'Orkiszowo–żytni', NULL, N'Chleb przepyszny ze słonecznikem i siemieniem lnianym, świetnie skomponowany, na naturalnym zakwasie. Bogaty w ziarna i doznania. Trwały i sycący. Pyyyyszny!', N'Ekologiczna mąka orkiszowa typ 1850 42%, ekologiczna mąka żytnia typ 2000 20%, woda, ekologiczne płatki owsiane, ziarno słonecznika, ekologiczne otręby owsiane, siemię lniane, zakwas, sól kłodawska', CAST(0.80 AS Decimal(10, 2)), N'SZT', 10.4800, 8.2900, 2, 0, 1, 0, 0, 1, 0, 0, 1, CAST(N'2018-10-16T13:30:57.577' AS DateTime), CAST(N'2018-12-04T20:17:18.183' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (2, 1, N'Płaskurka z kminkiem', NULL, N'Płaskurka to pradawna pszenica, odtworzona z banku genów. Chleb ciemny od wysokiej zawartości składników mineralnych, zawartych w płaskurce. Rozgrzewajacy organizm, a wraz z kminkiem regulujacy trawienie.', N'Ekologiczna mąka z płaskurki typ 1850, woda, zakwas, kminek, sól kłodawska', CAST(0.60 AS Decimal(10, 2)), N'SZT', 11.4300, 9.2400, 2, 0, 1, 0, 0, 0, 0, 0, 1, CAST(N'2018-10-16T13:30:57.690' AS DateTime), CAST(N'2018-12-04T18:41:23.993' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (3, 1, N'Gryczano-jaglany', NULL, N'Chleb gryczano-jaglany na zakwasie. Jedyny taki na rynku - wilgotny, choć w składzie nie ma glutenu. Naturalny i wyrośnięty', N'Ekologiczna mąka gryczana typ 1850 47%, ekologiczna mąka jaglana typ 1850 23%, woda, ziemniaki, siemię lniane, mąka ziemniaczana, zakwas bezglutenowy, ekologiczny ocet jablkowy, olej rzepakowy tłoczony na zimno nierafinowany, sól kłodawska', CAST(0.60 AS Decimal(10, 2)), N'SZT', 11.4300, 8.6900, 2, 0, 0, 1, 0, 0, 0, 0, 1, CAST(N'2018-10-16T13:30:57.807' AS DateTime), CAST(N'2018-12-04T20:08:53.753' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (4, 1, N'Orkiszowy z pomidorami', NULL, N'Chleb z bajecznie chrupiącą skórką i miękkim miaższem, dokładnie taki, jak u babci!', N'Ekologiczna maka orkiszowa typ 1850, woda, pomidory suszone na słońcu, zakwas, sól klodawska', CAST(0.70 AS Decimal(10, 2)), N'SZT', 11.4300, 9.2400, 2, 0, 0, 1, 0, 0, 0, 0, 1, CAST(N'2018-10-16T13:30:57.910' AS DateTime), CAST(N'2018-12-04T20:10:29.940' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (5, 1, N'Samopsza', NULL, N'Chleb z pierwotnej, dzikiej pszenicy, odtworzonej z banku genów. Jest to roslina lecznicza, a gluten z niej jest dobrze tolerowany nawet przez osoby na niego uczulone.', N'Ekologiczna maka z samopszy typ 1850, woda, zakwas, sól klodawska', CAST(0.60 AS Decimal(10, 2)), N'SZT', 13.3300, 11.1400, 2, 0, 0, 0, 1, 0, 0, 0, 1, CAST(N'2018-10-16T13:30:57.913' AS DateTime), CAST(N'2018-12-04T20:06:53.380' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (6, 1, N'Żytni z pestkami dyni', NULL, N'Typowy żytni chleb, ciężki i wilgotny. Trwały i podkręcony pestkami dyni.', N'Ekologiczna mąka żytnia typ 2000, woda, ekologiczne pestki dyni, zakwas, sól kłodawska', CAST(0.60 AS Decimal(10, 2)), N'SZT', 10.4800, 8.2900, 2, 0, 0, 0, 1, 0, 0, 0, 1, CAST(N'2018-10-16T13:30:57.913' AS DateTime), CAST(N'2018-12-04T18:41:03.677' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (7, 1, N'Chleb z krzycy', NULL, N'Chleb z krzycy - z pradawnego zyta, odtworzonego z banku genów. Chlebek ciemny, ciezki i slodkawy w smaku - pyyyyyszny', N'Ekologiczna mąka z krzycy typ 1850, woda, zakwas, sól klodawska', CAST(0.60 AS Decimal(10, 2)), N'KG', 10.4800, 8.2900, 2, 0, 1, 0, 0, 1, 0, 0, 0, CAST(N'2018-10-16T13:30:57.927' AS DateTime), CAST(N'2018-11-26T17:16:07.057' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (8, 2, N'Pasta ze słonecznika', NULL, N'Nasze smarowidła świetnie nadają się na kanapkę lub do naleśników. Pasta ze słonecznika ma bardzo dużo białka, smakuje pomidorami i chilli. Pyszna!', N'Slonecznik luskany, woda, pomidory suszone, kapary, czosnek, olej rzepakowy, przyprawy (w tym papryka)', CAST(0.20 AS Decimal(10, 2)), N'SZT', 11.4300, 9.5200, 2, 0, 1, 1, 1, 1, 0, 0, 1, CAST(N'2018-10-16T13:30:57.940' AS DateTime), CAST(N'2018-12-04T18:23:02.340' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (9, 2, N'Pasta z soczewicy', NULL, N'Pasta z soczewicy to nasz sztandarowy produkt. Polecamy zarówno w chłodne, jak i w gorące dni. Świetne smarowidło do kanapek, dobrze się też sprawdza jako dodatek smakowy do kaszy jaglanej lub ryżu. Dzieci ją lubią!', N'Soczewica czerwona ekologiczna, cebula, majonez, przyprawy
skład majonezu - olej rzepakowy, musztarda (woda, ocet, gorczyca, cukier, sól, przyprawy), woda, zóltka jaj kurzych (7,0%)', CAST(0.20 AS Decimal(10, 2)), N'SZT', 11.4300, 9.5200, 2, 0, 1, 1, 1, 1, 0, 0, 1, CAST(N'2018-10-16T13:30:57.940' AS DateTime), CAST(N'2018-12-04T18:22:57.167' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (10, 2, N'Powidła', NULL, N'Bez cukru, bez pektyn - sama śliwka - BOSKA!', N'Śliwka wegierka 100%', CAST(0.20 AS Decimal(10, 2)), N'SZT', 12.3800, 10.5200, 2, 0, 1, 1, 1, 1, 0, 0, 1, CAST(N'2018-10-16T13:30:57.943' AS DateTime), CAST(N'2018-12-04T20:27:39.453' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (11, 2, N'Masło orzechowe', NULL, N'PASTA - Orzeszki ziemne, sól', N'Orzeszki ziemne, sól kłodawska', CAST(0.20 AS Decimal(10, 2)), N'KG', 12.3800, 10.5200, 2, 0, 1, 1, 1, 1, 0, 0, 0, CAST(N'2018-10-16T13:30:57.950' AS DateTime), CAST(N'2018-11-26T17:16:35.453' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (12, 2, N'Pesto z pomidorów suszonych', NULL, N'Możesz używać i do kanapek i do makaronu, a nawet do nachosów :-). Pomidory suszone przełamane ostrością czosnku i przypraw - poezja!', N'Ekologiczne pomidory suszone na sloncu, olej rzepakowy tloczony na zimno, nierafinowany, czosnek, przyprawy', CAST(0.20 AS Decimal(10, 2)), N'SZT', 14.2900, 12.3800, 2, 0, 1, 1, 1, 1, 0, 0, 1, CAST(N'2018-10-16T13:30:57.953' AS DateTime), CAST(N'2018-12-04T20:28:06.047' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (13, 2, N'Pasta z pestek dyni', NULL, N'Pastą z dyni można smarować zarówno kanapkę, jak i mięso przed pieczeniem. Naleśniki też będą z nią wyborne.  Pestki z dyni są świetne na włosy, paznokcie i na męskość ;-).', N'Pestki dyni, suszone pomidory, olej rzepakowy tloczony na zimno, czosnek, przyprawy (w tym sos sojowy bezglutenowy)', CAST(0.20 AS Decimal(10, 2)), N'SZT', 14.2900, 12.3800, 2, 0, 1, 1, 1, 1, 0, 0, 1, CAST(N'2018-10-16T13:30:57.953' AS DateTime), CAST(N'2018-12-04T20:15:31.353' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (14, 2, N'Masło czekoladowe', NULL, N'PASTA - Orzeszki ziemne, miód, kakao, sól', N'Orzeszki ziemne, miód, kakao, sól kłodawska', CAST(0.20 AS Decimal(10, 2)), N'KG', 15.2400, 13.5000, 2, 0, 1, 1, 1, 1, 0, 0, 0, CAST(N'2018-10-16T13:30:57.970' AS DateTime), CAST(N'2018-11-26T17:16:44.023' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (15, 1, N'Płaskurka z żurawiną', NULL, N'Płaskurka to pradawna pszenica, odtworzona z banku genów. Chleb ciemny od wysokiej zawartości składników mineralnych, zawartych w płaskurce.  Prostota płaskurki i słodycz żurawiny świetnie ze sobą współgrają. 
Płaskurka', N'Mąka z płaskurki typ 1850*, woda, żurawina suszona z cukrem, zakwas, sól kłodawska', CAST(0.65 AS Decimal(10, 2)), N'KG', 12.3800, 10.2800, 2, 0, 0, 0, 0, 1, 0, 0, 1, CAST(N'2018-12-04T20:12:23.227' AS DateTime), CAST(N'2018-12-04T20:15:50.153' AS DateTime))
GO
INSERT [dbo].[tblProduct] ([ProductID], [CategoryID], [ProductName], [ShortDescription], [LongDescription], [Ingredients], [Weight], [UnitOfWeight], [UnitRetailPrice], [UnitWholesalePrice], [VATID], [IsMonday], [IsTuesday], [IsWednesday], [IsThursday], [IsFriday], [IsSaturday], [IsSunday], [IsActive], [DateCreated], [LastUpdated]) VALUES (16, 1, N'Płaskurka z oliwkami', NULL, N'Płaskurka to pradawna pszenica, odtworzona z banku genów. Chleb ciemny od wysokiej zawartości składników mineralnych, zawartych w płaskurce.
Oliwki podkreślają wytrawny charakter płaskurki.', N'Mąka z płaskurki typ 1850*, woda, oliwki zielone, zakwas, sól kłodawska', CAST(0.65 AS Decimal(10, 2)), N'KG', 12.3800, 9.9700, 2, 0, 0, 0, 0, 1, 0, 0, 1, CAST(N'2018-12-04T20:14:49.810' AS DateTime), CAST(N'2018-12-04T20:16:23.807' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[tblProduct] OFF
GO
