CREATE TABLE [dict].[tblVATRate]
(
	[VATID]    TINYINT IDENTITY (1, 1) NOT NULL ,
	[VATRate]  DECIMAL(5,4) NOT NULL ,
	[IsActive] BIT NOT NULL ,
	CONSTRAINT [PK_tblVATRates] PRIMARY KEY CLUSTERED ([VATID] ASC)
);
GO